# Generated by Django 3.2.5 on 2022-01-18 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0002_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='address',
            new_name='location',
        ),
    ]
