# Generated by Django 3.2.5 on 2022-01-19 20:25

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0004_jobapply'),
    ]

    operations = [
        migrations.CreateModel(
            name='InnerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True)),
                ('city', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('timing', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('desc', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobportal.category')),
            ],
        ),
    ]
