# Generated by Django 3.2.5 on 2022-01-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0006_jobapply_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapply',
            name='resume',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='news/'),
        ),
    ]
