# Generated by Django 3.2.5 on 2022-01-20 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0010_alter_jobapply_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='jobportal.category'),
            preserve_default=False,
        ),
    ]
