# Generated by Django 3.2.5 on 2022-01-20 18:41

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0015_auto_20220120_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True),
        ),
    ]
