# Generated by Django 3.2.5 on 2022-01-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0018_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=300)),
            ],
        ),
    ]
