# Generated by Django 3.2.5 on 2022-01-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0019_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('resume', models.FileField(default=None, max_length=250, null=True, upload_to='image')),
                ('carrier', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('salary', models.IntegerField()),
                ('exp', models.IntegerField()),
                ('desc', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
